DEFAULT: 
  camera_config: &default_camera_settings # See camera_variables.md documentation
      # Image format settings
      Width: 3548
      Height: 3548
      OffsetX: 0 
      OffsetY: 4
      BslColorSpace: "sRGB"
      PixelFormat: "BayerRG8"
      LUTEnable: True
      # Image Capture settings
      ExposureTime: 15000.0
      Gain: 0.0
      gamma: 1.0
      # Video settings
      AcquisitionFrameRateEnable: True
      AcquisitionFrameRate: 1.0
      # Auto settings
      AutoTargetBrightness: 0.5   # Mellem 0.0 og 1.0
      AutoFunction: "MinimizeGain" # "MinimizeGain", eller "MinimizeExposureTime"
      ExposureAuto: "Continuous"   # 'Off', 'Once', 'Continuous'
      AutoExposureTimeLowerLimit: 1.0
      AutoExposureTimeUpperLimit: 100000.0
      GainAuto: "Off"       # Off,' 'Once', 'Continuous'
      AutoGainLowerLimit: 0
      AutoGainUpperLimit: 24
      BalanceWhiteAuto: "Off"   # Off,' 'Once', 'Continuous'
  light_config: &default_light_settings
    led1: 100 # Strength in 8bit values (0-255)
    led2: 100 # Strength in 8bit values (0-255)
    led3: 100 # Strength in 8bit values (0-255

network:
  camera_switch_mac: "58:d6:1f:7c:65:03"
  microcontroller_switch_mac: "58:d6:1f:7c:65:03"
  unifi:
    host: "https://192.168.1.1:8443"
    username: "aau"
    password: "aau" 
    verify_ssl: false

# named hardware cofigurations for individiual rigs
setups:
  any:
    camera:
      ip: null
      switch_port: null
      serial: null
      settings: *default_camera_settings
    microcontroller:
      ip: 10.42.0.146
      port: 80
  
  rig1:
    camera:
      ip: 192.168.1.11
      switch_port: 1
      serial: null
      settings: *default_camera_settings
    microcontroller:
      ip: 192.168.1.101
      switch_port: 2
      port: 80
    light:
      settings: *default_light_settings
  
  rig2:
    camera:
      ip: 192.168.1.12
      switch_port: 3
      serial: null
      settings: *default_camera_settings
    microcontroller:
      switch_port: 4
      ip: 192.168.1.102
      port: 80
    light:
      settings: *default_light_settings
  
  rig3:
    camera:
      ip: 192.168.1.13
      switch_port: 5
      serial: null
      settings: *default_camera_settings
    microcontroller:
      ip: 192.168.1.103
      switch_port: 6
      port: 80
    light:
      settings: *default_light_settings

# Named camera configuration presets
camera_configs:
  default:
    <<: *default_camera_settings

  prototypeLongExp:
    <<: *default_camera_settings
    ExposureTime: 25000.0
    ExposureAuto: "Off"
    auto_gain: "Off"

  prototypeShortExp:
    <<: *default_camera_settings
    ExposureTime: 12500.0
    gain: 1.0
    ExposureAuto: "Off"
    auto_gain: "Off"

  action:
    <<: *default_camera_settings
    ExposureTime: 3500.0
    ExposureAuto: "Off"
    auto_gain: "Off"
    auto_gain_upper_limit: 18

  balance:
    <<: *default_camera_settings
    ExposureTime: 15000.0
    gain: 3.5
    ExposureAuto: "Off"
    auto_gain: "Off"
    AcquisitionFrameRate: 24

  longExposure:
    <<: *default_camera_settings
    ExposureTime: 75000.0
    gain: 1.0
    AutoTargetBrightness: 0.65
    ExposureAuto: "Off"
    auto_gain: "Off"
    AcquisitionFrameRate: 10

# Named lighting configuration presets
light_configs:
  default:
    <<: *default_light_settings

  bright:
    <<: *default_light_settings
    led1: 255
    led2: 255

  dim: 
    <<: *default_light_settings
    led1: 90
    led2: 90
    led3: 100

  #Light testing configurations
  demo_led1_full: 
    <<: *default_light_settings
    led1: 255
    led2: 0
    led3: 0
  
  demo_led2_full: 
    <<: *default_light_settings
    led1: 0
    led2: 255
    led3: 0

  demo_led3_full: 
    <<: *default_light_settings
    led1: 255
    led2: 0
    led3: 0

  demo_all: 
    <<: *default_light_settings
    led1: 100
    led2: 100
    led3: 100

  demo_pair1: 
    <<: *default_light_settings
    led1: 175
    led2: 175
    led3: 0

  demo_pair2: 
    <<: *default_light_settings
    led1: 175
    led2: 0
    led3: 175

  demo_pair3: 
    <<: *default_light_settings
    led1: 0
    led2: 175
    led3: 175